/* ==========================================================================
   KARAJGIKAR JEWELLERS CRM - AUTO WISHES SERVICE (autoWishService.js)
   ========================================================================== */

(function () {
  'use strict';

  window.CRM = window.CRM || {};

  const DEFAULT_BDAY_TEMPLATE = "Dear {name}, Karajgikar Jewellers wishes you a glittering and joyous Happy Birthday! May your day sparkle with happiness, good health & prosperity. - Karajgikar Jewellers, Solapur";
  const DEFAULT_ANNIV_TEMPLATE = "Dear {name}, Warmest greetings on your wedding anniversary from Karajgikar Jewellers! Wishing you both a lifetime of love, togetherness & prosperity. - Karajgikar Jewellers, Solapur";

  /**
   * Helper: format month and day as MM-DD
   */
  function getMonthDay(dateStr) {
    if (!dateStr) return null;
    const parts = dateStr.split('-');
    if (parts.length < 3) return null;
    return `${parts[1]}-${parts[2]}`;
  }

  /**
   * Automatically scan database and queue birthday/anniversary wishes for today.
   * Runs on CRM startup and periodic interval.
   */
  async function checkAndQueueDailyWishes(silent = false) {
    if (!window.CRM.db) return { queuedCount: 0 };

    try {
      // 1. Fetch config, customers, and existing messages
      const [appConfig, customers, existingMessages] = await Promise.all([
        window.CRM.db.get('settings', 'app_config'),
        window.CRM.customerService.getAllCustomers(),
        window.CRM.db.getAll('messages')
      ]);

      // Check if auto-dispatch is enabled (defaults to true)
      const autoEnabled = appConfig ? appConfig.autoWishesEnabled !== false : true;
      if (!autoEnabled) {
        console.log('[AutoWishService] Automatic wish dispatcher is disabled in settings.');
        return { queuedCount: 0, disabled: true };
      }

      const bdayTemplate = (appConfig && appConfig.bdayTemplate) ? appConfig.bdayTemplate : DEFAULT_BDAY_TEMPLATE;
      const annivTemplate = (appConfig && appConfig.annivTemplate) ? appConfig.annivTemplate : DEFAULT_ANNIV_TEMPLATE;

      const now = new Date();
      const currentYear = now.getFullYear();
      const currentMonth = String(now.getMonth() + 1).padStart(2, '0');
      const currentDay = String(now.getDate()).padStart(2, '0');
      const todayMMDD = `${currentMonth}-${currentDay}`;
      const todayFullDate = `${currentYear}-${currentMonth}-${currentDay}`;

      // Build a lookup set of already queued message IDs for today
      const alreadyQueuedSet = new Set();
      existingMessages.forEach(msg => {
        if (msg.eventDate === todayFullDate) {
          alreadyQueuedSet.add(`${msg.customerId}_${msg.type}`);
        }
      });

      const newMessagesToQueue = [];

      customers.forEach(cust => {
        // --- A. Birthday Check ---
        if (cust.dateOfBirth) {
          const custBdayMMDD = getMonthDay(cust.dateOfBirth);
          if (custBdayMMDD === todayMMDD) {
            const key = `${cust.id}_BIRTHDAY`;
            if (!alreadyQueuedSet.has(key)) {
              const msgText = bdayTemplate.replace(/\{name\}/gi, cust.fullName || 'Valued Customer');
              newMessagesToQueue.push({
                id: `MSG-BDAY-${cust.id}-${todayFullDate}`,
                customerId: cust.id,
                customerName: cust.fullName,
                mobile: cust.mobileNumber,
                channel: 'SMS',
                type: 'BIRTHDAY',
                message: msgText,
                status: 'PENDING',
                eventDate: todayFullDate,
                autoGenerated: true,
                createdAt: new Date().toISOString(),
                scheduledAt: new Date().toISOString()
              });
              alreadyQueuedSet.add(key);
            }
          }
        }

        // --- B. Anniversary Check ---
        if (cust.anniversaryDate) {
          const custAnnivMMDD = getMonthDay(cust.anniversaryDate);
          if (custAnnivMMDD === todayMMDD) {
            const key = `${cust.id}_ANNIVERSARY`;
            if (!alreadyQueuedSet.has(key)) {
              const msgText = annivTemplate.replace(/\{name\}/gi, cust.fullName || 'Valued Customer');
              newMessagesToQueue.push({
                id: `MSG-ANNIV-${cust.id}-${todayFullDate}`,
                customerId: cust.id,
                customerName: cust.fullName,
                mobile: cust.mobileNumber,
                channel: 'SMS',
                type: 'ANNIVERSARY',
                message: msgText,
                status: 'PENDING',
                eventDate: todayFullDate,
                autoGenerated: true,
                createdAt: new Date().toISOString(),
                scheduledAt: new Date().toISOString()
              });
              alreadyQueuedSet.add(key);
            }
          }
        }
      });

      // 2. Persist new messages into IndexedDB
      if (newMessagesToQueue.length > 0) {
        for (const msg of newMessagesToQueue) {
          await window.CRM.db.put('messages', msg);
        }
        console.log(`[AutoWishService] Successfully auto-queued ${newMessagesToQueue.length} daily wish(es) for today.`);

        if (!silent && window.showToast) {
          showToast(`✨ Automatically queued ${newMessagesToQueue.length} birthday/anniversary greeting(s) for today!`, 'success');
        }

        // Trigger message list refresh if on messages view
        const refreshEvent = new CustomEvent('crm-messages-updated');
        window.dispatchEvent(refreshEvent);
      } else {
        console.log('[AutoWishService] Daily wish check complete. No new wishes pending for today.');
      }

      return { queuedCount: newMessagesToQueue.length };
    } catch (err) {
      console.error('[AutoWishService] Error executing daily auto wish check:', err);
      return { error: err.message, queuedCount: 0 };
    }
  }

  // Export service to global namespace
  window.CRM.autoWishService = {
    checkAndQueueDailyWishes,
    DEFAULT_BDAY_TEMPLATE,
    DEFAULT_ANNIV_TEMPLATE
  };

})();
